import type { Metadata } from "next";
import Navbar from "@/component/Navbar";
import "./globals.css";
import AuthProvider from "./context/AuthProvider";
import { Toaster } from "@/components/ui/toaster";
import Footer from "@/component/Footer";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <AuthProvider>
      
      <body>
      <Navbar />
        {children}
        <Toaster/>
        <Footer />
      </body>
      </AuthProvider>
    </html>
  );
}
   